"""Common utilities.

Including, but not limited to:
-   typewriter-style printing,
-   artistic text printing,
-   the full-ish list of colors, and
-   a non-comprehensive list of escape codes.
"""


import dataclasses
import sys
import time

import art


def typing_print(text: str, runtime: float = 0.05, end: str | None = "\n") -> None:
    """Credit does not go to Nolan, as he stole it off the internet...

    But it works!
    Oh, and I modified it to add typing and a few other oddities.
    """
    for character in text:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(runtime)
    print("", end=end)


if __name__ == "__main__":
    typing_print("Hello! How you doing? Essay TBA.")
    typing_print(
        "Fourscore and seven years ago our fathers brought forth, on this continent, a new nation, conceived in liberty, and dedicated to the proposition that all men are created equal. Now we are engaged in a great civil war, testing whether that nation, or any nation so conceived, and so dedicated, can long endure. We are met on a great battle-field of that war. We have come to dedicate a portion of that field, as a final resting-place for those who here gave their lives, that that nation might live. It is altogether fitting and proper that we should do this. But, in a larger sense, we cannot dedicate, we cannot consecrate—we cannot hallow—this ground. The brave men, living and dead, who struggled here, have consecrated it far above our poor power to add or detract. The world will little note, nor long remember what we say here, but it can never forget what they did here. It is for us the living, rather, to be dedicated here to the unfinished work which they who fought here have thus far so nobly advanced. It is rather for us to be here dedicated to the great task remaining before us—that from these honored dead we take increased devotion to that cause for which they here gave the last full measure of devotion—that we here highly resolve that these dead shall not have died in vain—that this nation, under God, shall have a new birth of freedom, and that government of the people, by the people, for the people, shall not perish from the earth."  # pylint: disable=C0301
    )


def artistic_text(
    text: str,
    font: str = "random-medium",
    should_print: bool = True,
    typewriter: bool = True,
    speed: float = 0.025,
) -> str | None:
    """Draw text using the art package."""
    art_text = art.text2art(text, font=font)
    if should_print:
        if typewriter:
            typing_print(art_text, runtime=speed)
            return None

        print(art_text)
        return None
    return art.text2art(text, font=font)


# Credit where credit is due: https://www.wikipython.com/tkinter-ttk-tix/summary-information/colors/
COLORS: list[str] = [
    "snow",
    "ghost white",
    "white smoke",
    "gainsboro",
    "floral white",
    "old lace",
    "linen",
    "antique white",
    "papaya whip",
    "blanched almond",
    "bisque",
    "peach puff",
    "navajo white",
    "lemon chiffon",
    "mint cream",
    "azure",
    "alice blue",
    "lavender",
    "lavender blush",
    "misty rose",
    "dark slate gray",
    "dim gray",
    "slate gray",
    "light slate gray",
    "gray",
    "light gray",
    "midnight blue",
    "navy",
    "cornflower blue",
    "dark slate blue",
    "slate blue",
    "medium slate blue",
    "light slate blue",
    "medium blue",
    "royal blue",
    "blue",
    "dodger blue",
    "deep sky blue",
    "sky blue",
    "light sky blue",
    "steel blue",
    "light steel blue",
    "light blue",
    "powder blue",
    "pale turquoise",
    "dark turquoise",
    "medium turquoise",
    "turquoise",
    "cyan",
    "light cyan",
    "cadet blue",
    "medium aquamarine",
    "aquamarine",
    "dark green",
    "dark olive green",
    "dark sea green",
    "sea green",
    "medium sea green",
    "light sea green",
    "pale green",
    "spring green",
    "lawn green",
    "medium spring green",
    "green yellow",
    "lime green",
    "yellow green",
    "forest green",
    "olive drab",
    "dark khaki",
    "khaki",
    "pale goldenrod",
    "light goldenrod yellow",
    "light yellow",
    "yellow",
    "gold",
    "light goldenrod",
    "goldenrod",
    "dark goldenrod",
    "rosy brown",
    "indian red",
    "saddle brown",
    "sandy brown",
    "dark salmon",
    "salmon",
    "light salmon",
    "orange",
    "dark orange",
    "coral",
    "light coral",
    "tomato",
    "orange red",
    "red",
    "hot pink",
    "deep pink",
    "pink",
    "light pink",
    "pale violet red",
    "maroon",
    "medium violet red",
    "violet red",
    "medium orchid",
    "dark orchid",
    "dark violet",
    "blue violet",
    "purple",
    "medium purple",
    "thistle",
    "snow2",
    "snow3",
    "snow4",
    "seashell2",
    "seashell3",
    "seashell4",
    "AntiqueWhite1",
    "AntiqueWhite2",
    "AntiqueWhite3",
    "AntiqueWhite4",
    "bisque2",
    "bisque3",
    "bisque4",
    "PeachPuff2",
    "PeachPuff3",
    "PeachPuff4",
    "NavajoWhite2",
    "NavajoWhite3",
    "NavajoWhite4",
    "LemonChiffon2",
    "LemonChiffon3",
    "LemonChiffon4",
    "cornsilk2",
    "cornsilk3",
    "cornsilk4",
    "ivory2",
    "ivory3",
    "ivory4",
    "honeydew2",
    "honeydew3",
    "honeydew4",
    "LavenderBlush2",
    "LavenderBlush3",
    "LavenderBlush4",
    "MistyRose2",
    "MistyRose3",
    "MistyRose4",
    "azure2",
    "azure3",
    "azure4",
    "SlateBlue1",
    "SlateBlue2",
    "SlateBlue3",
    "SlateBlue4",
    "RoyalBlue1",
    "RoyalBlue2",
    "RoyalBlue3",
    "RoyalBlue4",
    "blue2",
    "blue4",
    "DodgerBlue2",
    "DodgerBlue3",
    "DodgerBlue4",
    "SteelBlue1",
    "SteelBlue2",
    "SteelBlue3",
    "SteelBlue4",
    "DeepSkyBlue2",
    "DeepSkyBlue3",
    "DeepSkyBlue4",
    "SkyBlue1",
    "SkyBlue2",
    "SkyBlue3",
    "SkyBlue4",
    "LightSkyBlue1",
    "LightSkyBlue2",
    "LightSkyBlue3",
    "LightSkyBlue4",
    "Slategray1",
    "Slategray2",
    "Slategray3",
    "Slategray4",
    "LightSteelBlue1",
    "LightSteelBlue2",
    "LightSteelBlue3",
    "LightSteelBlue4",
    "LightBlue1",
    "LightBlue2",
    "LightBlue3",
    "LightBlue4",
    "LightCyan2",
    "LightCyan3",
    "LightCyan4",
    "PaleTurquoise1",
    "PaleTurquoise2",
    "PaleTurquoise3",
    "PaleTurquoise4",
    "CadetBlue1",
    "CadetBlue2",
    "CadetBlue3",
    "CadetBlue4",
    "turquoise1",
    "turquoise2",
    "turquoise3",
    "turquoise4",
    "cyan2",
    "cyan3",
    "cyan4",
    "DarkSlategray1",
    "DarkSlategray2",
    "DarkSlategray3",
    "DarkSlategray4",
    "aquamarine2",
    "aquamarine4",
    "DarkSeaGreen1",
    "DarkSeaGreen2",
    "DarkSeaGreen3",
    "DarkSeaGreen4",
    "SeaGreen1",
    "SeaGreen2",
    "SeaGreen3",
    "PaleGreen1",
    "PaleGreen2",
    "PaleGreen3",
    "PaleGreen4",
    "SpringGreen2",
    "SpringGreen3",
    "SpringGreen4",
    "green2",
    "green3",
    "green4",
    "chartreuse2",
    "chartreuse3",
    "chartreuse4",
    "OliveDrab1",
    "OliveDrab2",
    "OliveDrab4",
    "DarkOliveGreen1",
    "DarkOliveGreen2",
    "DarkOliveGreen3",
    "DarkOliveGreen4",
    "khaki1",
    "khaki2",
    "khaki3",
    "khaki4",
    "LightGoldenrod1",
    "LightGoldenrod2",
    "LightGoldenrod3",
    "LightGoldenrod4",
    "LightYellow2",
    "LightYellow3",
    "LightYellow4",
    "yellow2",
    "yellow3",
    "yellow4",
    "gold2",
    "gold3",
    "gold4",
    "goldenrod1",
    "goldenrod2",
    "goldenrod3",
    "goldenrod4",
    "DarkGoldenrod1",
    "DarkGoldenrod2",
    "DarkGoldenrod3",
    "DarkGoldenrod4",
    "RosyBrown1",
    "RosyBrown2",
    "RosyBrown3",
    "RosyBrown4",
    "IndianRed1",
    "IndianRed2",
    "IndianRed3",
    "IndianRed4",
    "sienna1",
    "sienna2",
    "sienna3",
    "sienna4",
    "burlywood1",
    "burlywood2",
    "burlywood3",
    "burlywood4",
    "wheat1",
    "wheat2",
    "wheat3",
    "wheat4",
    "tan1",
    "tan2",
    "tan4",
    "chocolate1",
    "chocolate2",
    "chocolate3",
    "firebrick1",
    "firebrick2",
    "firebrick3",
    "firebrick4",
    "brown1",
    "brown2",
    "brown3",
    "brown4",
    "salmon1",
    "salmon2",
    "salmon3",
    "salmon4",
    "LightSalmon2",
    "LightSalmon3",
    "LightSalmon4",
    "orange2",
    "orange3",
    "orange4",
    "DarkOrange1",
    "DarkOrange2",
    "DarkOrange3",
    "DarkOrange4",
    "coral1",
    "coral2",
    "coral3",
    "coral4",
    "tomato2",
    "tomato3",
    "tomato4",
    "OrangeRed2",
    "OrangeRed3",
    "OrangeRed4",
    "red2",
    "red3",
    "red4",
    "DeepPink2",
    "DeepPink3",
    "DeepPink4",
    "HotPink1",
    "HotPink2",
    "HotPink3",
    "HotPink4",
    "pink1",
    "pink2",
    "pink3",
    "pink4",
    "LightPink1",
    "LightPink2",
    "LightPink3",
    "LightPink4",
    "PaleVioletRed1",
    "PaleVioletRed2",
    "PaleVioletRed3",
    "PaleVioletRed4",
    "maroon1",
    "maroon2",
    "maroon3",
    "maroon4",
    "VioletRed1",
    "VioletRed2",
    "VioletRed3",
    "VioletRed4",
    "magenta2",
    "magenta3",
    "magenta4",
    "orchid1",
    "orchid2",
    "orchid3",
    "orchid4",
    "plum1",
    "plum2",
    "plum3",
    "plum4",
    "MediumOrchid1",
    "MediumOrchid2",
    "MediumOrchid3",
    "MediumOrchid4",
    "DarkOrchid1",
    "DarkOrchid2",
    "DarkOrchid3",
    "DarkOrchid4",
    "purple1",
    "purple2",
    "purple3",
    "purple4",
    "MediumPurple1",
    "MediumPurple2",
    "MediumPurple3",
    "MediumPurple4",
    "thistle1",
    "thistle2",
    "thistle3",
    "thistle4",
    "grey1",
    "grey2",
    "grey3",
    "grey4",
    "grey5",
    "grey6",
    "grey7",
    "grey8",
    "grey9",
    "grey10",
    "grey11",
    "grey12",
    "grey13",
    "grey14",
    "grey15",
    "grey16",
    "grey17",
    "grey18",
    "grey19",
    "grey20",
    "grey21",
    "grey22",
    "grey23",
    "grey24",
    "grey25",
    "grey26",
    "grey27",
    "grey28",
    "grey29",
    "grey30",
    "grey31",
    "grey32",
    "grey33",
    "grey34",
    "grey35",
    "grey36",
    "grey37",
    "grey38",
    "grey39",
    "grey40",
    "grey42",
    "grey43",
    "grey44",
    "grey45",
    "grey46",
    "grey47",
    "grey48",
    "grey49",
    "grey50",
    "grey51",
    "grey52",
    "grey53",
    "grey54",
    "grey55",
    "grey56",
    "grey57",
    "grey58",
    "grey59",
    "grey60",
    "grey61",
    "grey62",
    "grey63",
    "grey64",
    "grey65",
    "grey66",
    "grey67",
    "grey68",
    "grey69",
    "grey70",
    "grey71",
    "grey72",
    "grey73",
    "grey74",
    "grey75",
    "grey76",
    "grey77",
    "grey78",
    "grey79",
    "grey80",
    "grey81",
    "grey82",
    "grey83",
    "grey84",
    "grey85",
    "grey86",
    "grey87",
    "grey88",
    "grey89",
    "grey90",
    "grey91",
    "grey92",
    "grey93",
    "grey94",
    "grey95",
    "grey97",
    "grey98",
    "grey99",
]

# credit where credit is due: https://stackoverflow.com/a/287944
@dataclasses.dataclass
class BColors:
    """Non-comprehensive list of escape codes.

    From:https://svn.blender.org/svnroot/bf-blender/trunk/blender/build_files/scons/tools/bcolors.py
    """

    HEADER = "\033[95m"
    OKBLUE = "\033[94m"
    OKCYAN = "\033[96m"
    OKGREEN = "\033[92m"
    WARNING = "\033[93m"
    FAIL = "\033[91m"
    ENDC = "\033[0m"
    BOLD = "\033[1m"
    UNDERLINE = "\033[4m"
