"""Program: abstract_art.py - Make abstract art with turtles.

"Use random colors, randomly sized circles, and randomly sized squares
to create abstract art that is different each time you run the program."
"""


import random
import turtle as trtl

painter = trtl.Turtle()
painter.speed(0)
# See /art/turtles/a_row_of_colored_squares.py for original code.
def square(s):
    """Make a square.
    """
    for i in range(4):
        painter.forward(s)
        painter.left(90)


# Credit where credit is due: https://www.wikipython.com/tkinter-ttk-tix/summary-information/colors/
# *note:* list modified to minimize size
colors = [
    "snow",
    "ghost white",
    "white smoke",
    "gainsboro",
    "floral white",
    "old lace",
    "linen",
    "antique white",
    "papaya whip",
    "blanched almond",
    "bisque",
    "peach puff",
    "navajo white",
    "lemon chiffon",
    "mint cream",
    "azure",
    "alice blue",
    "lavender",
    "lavender blush",
    "misty rose",
    "dark slate gray",
    "dim gray",
    "slate gray",
    "light slate gray",
    "gray",
    "light gray",
    "midnight blue",
    "navy",
    "cornflower blue",
    "dark slate blue",
    "slate blue",
    "medium slate blue",
    "light slate blue",
    "medium blue",
    "royal blue",
    "blue",
    "dodger blue",
    "deep sky blue",
    "sky blue",
    "light sky blue",
    "steel blue",
    "light steel blue",
    "light blue",
    "powder blue",
    "pale turquoise",
    "dark turquoise",
    "medium turquoise",
    "turquoise",
    "cyan",
    "light cyan",
    "cadet blue",
    "medium aquamarine",
    "aquamarine",
    "dark green",
    "dark olive green",
    "dark sea green",
    "sea green",
    "medium sea green",
    "light sea green",
    "pale green",
    "spring green",
    "lawn green",
    "medium spring green",
    "green yellow",
    "lime green",
    "yellow green",
    "forest green",
    "olive drab",
    "dark khaki",
    "khaki",
    "pale goldenrod",
    "light goldenrod yellow",
    "light yellow",
    "yellow",
    "gold",
    "light goldenrod",
    "goldenrod",
    "dark goldenrod",
    "rosy brown",
    "indian red",
    "saddle brown",
    "sandy brown",
    "dark salmon",
    "salmon",
    "light salmon",
    "orange",
    "dark orange",
    "coral",
    "light coral",
    "tomato",
    "orange red",
    "red",
    "hot pink",
    "deep pink",
    "pink",
    "light pink",
    "pale violet red",
    "maroon",
    "medium violet red",
    "violet red",
    "medium orchid",
    "dark orchid",
    "dark violet",
    "blue violet",
    "purple",
    "medium purple",
    "thistle",
    "snow4",
    "seashell4",
    "AntiqueWhite1",
    "AntiqueWhite4",
    "bisque4",
    "PeachPuff4",
    "NavajoWhite4",
    "LemonChiffon4",
    "cornsilk4",
    "ivory4",
    "honeydew4",
    "LavenderBlush4",
    "MistyRose4",
    "azure4",
    "SlateBlue1",
    "SlateBlue4",
    "RoyalBlue1",
    "RoyalBlue4",
    "blue4",
    "DodgerBlue4",
    "SteelBlue1",
    "SteelBlue4",
    "DeepSkyBlue4",
    "SkyBlue1",
    "SkyBlue4",
    "LightSkyBlue1",
    "LightSkyBlue4",
    "Slategray1",
    "Slategray4",
    "LightSteelBlue1",
    "LightSteelBlue4",
    "LightBlue1",
    "LightBlue4",
    "LightCyan4",
    "PaleTurquoise1",
    "PaleTurquoise4",
    "CadetBlue1",
    "CadetBlue4",
    "turquoise1",
    "turquoise4",
    "cyan4",
    "DarkSlategray1",
    "DarkSlategray4",
    "aquamarine4",
    "DarkSeaGreen1",
    "DarkSeaGreen4",
    "SeaGreen1",
    "SeaGreen3",
    "PaleGreen1",
    "PaleGreen4",
    "SpringGreen4",
    "green4",
    "chartreuse4",
    "OliveDrab1",
    "OliveDrab4",
    "DarkOliveGreen1",
    "DarkOliveGreen4",
    "khaki1",
    "khaki4",
    "LightGoldenrod1",
    "LightGoldenrod4",
    "LightYellow4",
    "yellow4",
    "gold4",
    "goldenrod1",
    "goldenrod4",
    "DarkGoldenrod1",
    "DarkGoldenrod4",
    "RosyBrown1",
    "RosyBrown4",
    "IndianRed1",
    "IndianRed4",
    "sienna1",
    "sienna4",
    "burlywood1",
    "burlywood4",
    "wheat1",
    "wheat4",
    "tan1",
    "tan4",
    "chocolate1",
    "chocolate3",
    "firebrick1",
    "firebrick4",
    "brown1",
    "brown4",
    "salmon1",
    "salmon4",
    "LightSalmon4",
    "orange4",
    "DarkOrange4",
    "coral1",
    "coral4",
    "tomato4",
    "OrangeRed4",
    "red4",
    "DeepPink4",
    "HotPink1",
    "HotPink4",
    "pink1",
    "pink4",
    "LightPink1",
    "LightPink4",
    "PaleVioletRed1",
    "PaleVioletRed4",
    "maroon1",
    "maroon4",
    "VioletRed1",
    "VioletRed4",
    "magenta4",
    "orchid1",
    "orchid4",
    "plum1",
    "plum4",
    "MediumOrchid1",
    "MediumOrchid4",
    "DarkOrchid1",
    "DarkOrchid4",
    "purple1",
    "purple4",
    "MediumPurple1",
    "MediumPurple4",
    "thistle1",
    "thistle4",
    "grey1",
    "grey20",
    "grey50",
    "grey75",
    "grey99",
]


def generate_fill_color():
    """Generate a color, and begin fill.
    """
    painter.begin_fill()
    painter.fillcolor(colors[random.randint(0, len(colors) - 1)])


for i in range(10):
    painter.forward(random.randint(0, 360))
    generate_fill_color()
    square(random.randint(10, 50))
    painter.end_fill()
    painter.forward(random.randint(20, 100))
    painter.setheading(random.randint(0, 360))
    generate_fill_color()
    painter.circle(random.randint(5, 30))
    painter.end_fill()


wn = trtl.Screen()
wn.mainloop()
